stages:
  - build
  - test
  - deploy

build:
  image: node:latest
  stage: build
  script:
    - echo "Installing dependencies......"
    - npm install
    - echo "Building react app......"
    - npm run build
  only:
    - master
    - dev

test:
  image: node:latest
  stage: test
  script:
    - echo "Installing dependencies......"
    - npm install
    - echo "Running react test suite......"
    - npm run test
  only:
    - master
    - dev

deploy-dev:
  image: ruby:latest
  stage: deploy
  script:
    - echo "Deploying to Heroku (dev)..."
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_DEV --api-key=$HEROKU_API_KEY
  only:
    - dev

deploy-prod:
  image: ruby:latest
  stage: deploy
  script:
    - echo "Deploying to Heroku..."
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_DEPLOY --api-key=$HEROKU_API_KEY
  only:
    - master
