stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

build:
  image: node:latest
  stage: build
  script:
    - echo "Installing dependencies......"
    - npm install
    - echo "Building react app......"
    - npm run build
  artifacts:
    paths:
      - ./build
  only:
    - master

test:
  image: node:latest
  stage: test
  script:
    - echo "Installing dependencies......"
    - npm install
    - echo "Running react test suite......"
    - npm run test
  only:
    - master

deploy:
  stage: deploy
  variables:
    HEROKU_API_KEY: $HEROKU_API_KEY
  script:
    - echo "Deploying to Heroku..."
    - apt-get update -qy
    - apt-get install -y curl
    - curl https://cli-assets.heroku.com/install.sh | sh
    - heroku login -i
    - heroku git:remote -a drp13-2023
    - git push heroku master
  only:
    - master
